USE [BI Staging];

SET CONCAT_NULL_YIELDS_NULL OFF

SELECT
TRFAM#
,TRSEQ#
,TRCODE
,TRMODF
,TRMOD2
,TRMOD3
,TRPDAT
,TRTDAT
,TIIN#1
,TRLOC
,TRADR#
,TRRDR#
,TRNORD
,TRNPCP
,TRAMT
,TRDIAG
,TRDIG2
,TRDIG3
,TRDIG4
,CPU_TRANS.Entity
,CASE
WHEN CPU_CHARG_loc.CHMCD1 IS NOT NULL THEN CPU_CHARG_loc.CHMCD1
ELSE CPU_CHARG_noloc.CHMCD1
END as 'CHMCD1'
,CASE
WHEN CPU_CHARG_loc.CHMCD1 IS NOT NULL THEN CPU_CHARG_loc.CHTYPE
ELSE CPU_CHARG_noloc.CHTYPE
END as 'CHTYPE'
,CASE
WHEN CPU_CHARG_loc.CHMCD1 IS NOT NULL THEN CPU_CHARG_loc.CHSUBT
ELSE CPU_CHARG_noloc.CHSUBT
END as 'CHSUBT'
,CASE
WHEN CPU_CHARG_loc.CHMCD1 IS NOT NULL THEN CPU_CHARG_loc.CHDESC
ELSE CPU_CHARG_noloc.CHDESC
END as 'CHDESC'
,CASE
WHEN PATINDEX('%[^,] %', CPU_DOCTR_loc.DRNAME) > 0 THEN LEFT(CPU_DOCTR_loc.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_loc.DRNAME))
WHEN PATINDEX('%[^,] %', CPU_DOCTR_noloc.DRNAME) > 0 THEN LEFT(CPU_DOCTR_noloc.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_noloc.DRNAME))
WHEN CPU_DOCTR_loc.DRNAME IS NOT NULL THEN CPU_DOCTR_loc.DRNAME
ELSE CPU_DOCTR_noloc.DRNAME
END as 'Referring Physician'
,TaskAccount.NAME as "Referring Organization"
,TaskAccount.LKL3__Practice_Type__c as "Referring Organization Type"
,ISNULL(ParentAccount.NAME, TaskAccount.NAME) as "Referring Parent Organization"
,TaskAccount.GROUP__C as "Referring Medical Group"

INTO #CPU_TRANS_Charges

FROM
CPU_TRANS
LEFT JOIN CPU_CHARG as "CPU_CHARG_loc"
ON CPU_TRANS.TRCODE = CPU_CHARG_loc.CHCOD AND CPU_TRANS.TRLOC = CPU_CHARG_loc.CHLOC AND CPU_TRANS.Entity LIKE CPU_CHARG_loc.Entity
LEFT JOIN CPU_CHARG as "CPU_CHARG_noloc"
ON CPU_TRANS.TRCODE = CPU_CHARG_noloc.CHCOD AND 1 = CPU_CHARG_noloc.CHLOC AND CPU_TRANS.Entity LIKE CPU_CHARG_noloc.Entity
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_loc"
ON CPU_TRANS.TRRDR# = CPU_DOCTR_loc.DRNUM AND CPU_TRANS.TRLOC = CPU_DOCTR_loc.DRLOC AND CPU_TRANS.Entity LIKE CPU_DOCTR_loc.Entity
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_noloc"
ON CPU_TRANS.TRRDR# = CPU_DOCTR_noloc.DRNUM AND 1 = CPU_DOCTR_noloc.DRLOC AND CPU_TRANS.Entity LIKE CPU_DOCTR_noloc.Entity
LEFT JOIN ZZ_Contact
ON ISNULL(CPU_DOCTR_loc.DRUPIN, CPU_DOCTR_noloc.DRUPIN) LIKE ZZ_Contact.LKL3__NPI__C
AND NOT ZZ_Contact.LKL3__NPI__C = ''
LEFT JOIN ZZ_Account as TaskAccount
ON ZZ_Contact.ACCOUNTID LIKE TaskAccount.ID
LEFT JOIN ZZ_Account as ParentAccount
ON TaskAccount.PARENTID LIKE ParentAccount.ID

WHERE TRTYPE LIKE 'C'
--AND TRMODF NOT LIKE '*P'



SELECT
'Charges' as "Type"
,TRFAM# as "Account Number"
,CHMCD1 as "CPT Code"
,TRMODF + ' ' + TRMOD2 + ' ' + TRMOD3 as "Modifiers"
,CHDESC as "Description"
,CTDESC as "Category"
,TRDIAG+' '+TRDIG2+' '+TRDIG3+' '+TRDIG4 as "Diagnosis Codes"
,TRPDAT as "Date of Entry"
,TRPDAT as "Date of Charge"
,TRTDAT as "Date of Service"
,InsuranceName as "Insurance"
,ISNULL(FinancialClass, 'Unknown') as "Financial Class"
,InsuranceName as "Insurance of Specific Transaction"
,ISNULL(FinancialClass, 'Unknown') as "Financial Class of Specific Transaction"
,CASE
WHEN #CPU_TRANS_Charges.Entity LIKE 'PM' AND #CPU_TRANS_Charges.TRLOC = 1
THEN CASE
	WHEN TRCODE = 411 THEN 'Medical-UVPM'
	WHEN TRCODE = 430 THEN 'UVPM'
	WHEN TRCODE = 431 THEN 'UVPM'
	WHEN TRCODE = 434 THEN 'UVPM'
	WHEN TRCODE = 518 THEN 'UVPM'
	WHEN TRCODE = 585 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 600 THEN 'UVPM'
	WHEN TRCODE = 621 THEN 'PT-UVPM'
	WHEN TRCODE = 631 THEN 'PT-UVPM'
	WHEN TRCODE = 666 THEN 'UVPM'
	WHEN TRCODE = 700 THEN 'Psych-UVPM'
	WHEN TRCODE = 777 THEN 'UVPM'
	WHEN TRCODE = 800 THEN 'EMG-UVPM'
	WHEN TRCODE = 900 THEN 'UVPM'
	WHEN TRCODE = 950 THEN 'UVPM'
	WHEN TRCODE = 999 THEN 'UVPM'
	WHEN TRCODE = 1100 THEN 'UVPM'
	WHEN TRCODE = 1101 THEN 'UVPM'
	WHEN TRCODE = 1845 THEN 'PT-UVPM'
	WHEN TRCODE = 1885 THEN 'Medical-UVPM'
	WHEN TRCODE = 3288 THEN 'UVPM'
	WHEN TRCODE = 3807 THEN 'PT-UVPM'
	WHEN TRCODE = 3908 THEN 'PT-UVPM'
	WHEN TRCODE = 3915 THEN 'PT-UVPM'
	WHEN TRCODE = 4595 THEN 'PT-UVPM'
	WHEN TRCODE = 6040 THEN 'Medical-UVPM'
	WHEN TRCODE = 6666 THEN 'UVPM'
	WHEN TRCODE = 7335 THEN 'Medical-UVPM'
	WHEN TRCODE = 8427 THEN 'UVPM'
	WHEN TRCODE = 8431 THEN 'UVPM'
	WHEN TRCODE = 8510 THEN 'UVPM'
	WHEN TRCODE = 8539 THEN 'UVPM'
	WHEN TRCODE = 8540 THEN 'UVPM'
	WHEN TRCODE = 8542 THEN 'UVPM'
	WHEN TRCODE = 8553 THEN 'UVPM'
	WHEN TRCODE = 8730 THEN 'UVPM'
	WHEN TRCODE = 8978 THEN 'PT-UVPM'
	WHEN TRCODE = 8979 THEN 'PT-UVPM'
	WHEN TRCODE = 8980 THEN 'PT-UVPM'
	WHEN TRCODE = 8981 THEN 'PT-UVPM'
	WHEN TRCODE = 8982 THEN 'PT-UVPM'
	WHEN TRCODE = 8983 THEN 'PT-UVPM'
	WHEN TRCODE = 8984 THEN 'PT-UVPM'
	WHEN TRCODE = 8985 THEN 'PT-UVPM'
	WHEN TRCODE = 8986 THEN 'PT-UVPM'
	WHEN TRCODE = 8987 THEN 'PT-UVPM'
	WHEN TRCODE = 8988 THEN 'PT-UVPM'
	WHEN TRCODE = 8989 THEN 'PT-UVPM'
	WHEN TRCODE = 8990 THEN 'PT-UVPM'
	WHEN TRCODE = 8991 THEN 'PT-UVPM'
	WHEN TRCODE = 8992 THEN 'PT-UVPM'
	WHEN TRCODE = 9070 THEN 'Medical-UVPM'
	WHEN TRCODE = 9907 THEN 'Psych-UVPM'
	WHEN TRCODE = 9981 THEN 'UVPM'
	WHEN TRCODE = 9988 THEN 'UVPM'
	WHEN TRCODE = 9998 THEN 'UVPM'
	WHEN TRCODE = 9999 THEN 'UVPM'
	WHEN TRCODE = 20550 THEN 'Medical-UVPM'
	WHEN TRCODE = 20551 THEN 'Medical-UVPM'
	WHEN TRCODE = 20552 THEN 'Medical-UVPM'
	WHEN TRCODE = 20553 THEN 'Medical-UVPM'
	WHEN TRCODE = 20605 THEN 'Medical-UVPM'
	WHEN TRCODE = 20610 THEN 'Medical-UVPM'
	WHEN TRCODE = 64405 THEN 'Medical-UVPM'
	WHEN TRCODE = 64450 THEN 'Medical-UVPM'
	WHEN TRCODE = 64505 THEN 'Medical-UVPM'
	WHEN TRCODE = 64550 THEN 'PT-UVPM'
	WHEN TRCODE = 64612 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 64613 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 64614 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 64615 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 64616 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 64999 THEN 'Medical-UVPM'
	WHEN TRCODE = 77002 THEN 'Medical-UVPM'
	WHEN TRCODE = 80101 THEN 'UVPM'
	WHEN TRCODE = 80104 THEN 'UVPM'
	WHEN TRCODE = 80301 THEN 'UVPM'
	WHEN TRCODE = 81003 THEN 'UVPM'
	WHEN TRCODE = 82055 THEN 'UVPM'
	WHEN TRCODE = 82570 THEN 'UVPM'
	WHEN TRCODE = 83986 THEN 'UVPM'
	WHEN TRCODE = 84311 THEN 'UVPM'
	WHEN TRCODE = 85610 THEN 'UVPM'
	WHEN TRCODE = 90785 THEN 'Psych-UVPM'
	WHEN TRCODE = 90791 THEN 'Psych-UVPM'
	WHEN TRCODE = 90792 THEN 'Psych-UVPM'
	WHEN TRCODE = 90801 THEN 'Psych-UVPM'
	WHEN TRCODE = 90804 THEN 'Psych-UVPM'
	WHEN TRCODE = 90806 THEN 'Psych-UVPM'
	WHEN TRCODE = 90808 THEN 'Psych-UVPM'
	WHEN TRCODE = 90832 THEN 'Psych-UVPM'
	WHEN TRCODE = 90834 THEN 'Psych-UVPM'
	WHEN TRCODE = 90837 THEN 'Psych-UVPM'
	WHEN TRCODE = 90839 THEN 'Psych-UVPM'
	WHEN TRCODE = 90847 THEN 'Psych-UVPM'
	WHEN TRCODE = 90853 THEN 'Psych-UVPM'
	WHEN TRCODE = 90875 THEN 'Psych-UVPM'
	WHEN TRCODE = 90876 THEN 'Psych-UVPM'
	WHEN TRCODE = 90901 THEN 'PT-UVPM'
	WHEN TRCODE = 95860 THEN 'EMG-UVPM'
	WHEN TRCODE = 95861 THEN 'EMG-UVPM'
	WHEN TRCODE = 95863 THEN 'EMG-UVPM'
	WHEN TRCODE = 95867 THEN 'EMG-UVPM'
	WHEN TRCODE = 95869 THEN 'EMG-UVPM'
	WHEN TRCODE = 95870 THEN 'EMG-UVPM'
	WHEN TRCODE = 95874 THEN 'Botox (Medical)-UVPM'
	WHEN TRCODE = 95885 THEN 'EMG-UVPM'
	WHEN TRCODE = 95886 THEN 'EMG-UVPM'
	WHEN TRCODE = 95887 THEN 'EMG-UVPM'
	WHEN TRCODE = 95888 THEN 'EMG-UVPM'
	WHEN TRCODE = 95900 THEN 'EMG-UVPM'
	WHEN TRCODE = 95903 THEN 'EMG-UVPM'
	WHEN TRCODE = 95904 THEN 'EMG-UVPM'
	WHEN TRCODE = 95907 THEN 'EMG-UVPM'
	WHEN TRCODE = 95908 THEN 'EMG-UVPM'
	WHEN TRCODE = 95909 THEN 'EMG-UVPM'
	WHEN TRCODE = 95910 THEN 'EMG-UVPM'
	WHEN TRCODE = 95911 THEN 'EMG-UVPM'
	WHEN TRCODE = 95912 THEN 'EMG-UVPM'
	WHEN TRCODE = 95913 THEN 'EMG-UVPM'
	WHEN TRCODE = 95933 THEN 'EMG-UVPM'
	WHEN TRCODE = 95934 THEN 'EMG-UVPM'
	WHEN TRCODE = 95936 THEN 'EMG-UVPM'
	WHEN TRCODE = 95937 THEN 'EMG-UVPM'
	WHEN TRCODE = 95970 THEN 'Medical-UVPM'
	WHEN TRCODE = 95972 THEN 'Medical-UVPM'
	WHEN TRCODE = 95973 THEN 'Medical-UVPM'
	WHEN TRCODE = 96101 THEN 'Psych-UVPM'
	WHEN TRCODE = 96103 THEN 'Psych-UVPM'
	WHEN TRCODE = 96118 THEN 'Psych-UVPM'
	WHEN TRCODE = 96152 THEN 'Psych-UVPM'
	WHEN TRCODE = 96372 THEN 'Medical-UVPM'
	WHEN TRCODE = 96999 THEN 'Medical-UVPM'
	WHEN TRCODE = 97001 THEN 'PT-UVPM'
	WHEN TRCODE = 97002 THEN 'PT-UVPM'
	WHEN TRCODE = 97012 THEN 'PT-UVPM'
	WHEN TRCODE = 97014 THEN 'PT-UVPM'
	WHEN TRCODE = 97033 THEN 'PT-UVPM'
	WHEN TRCODE = 97035 THEN 'PT-UVPM'
	WHEN TRCODE = 97110 THEN 'PT-UVPM'
	WHEN TRCODE = 97112 THEN 'PT-UVPM'
	WHEN TRCODE = 97116 THEN 'PT-UVPM'
	WHEN TRCODE = 97124 THEN 'PT-UVPM'
	WHEN TRCODE = 97140 THEN 'PT-UVPM'
	WHEN TRCODE = 97530 THEN 'PT-UVPM'
	WHEN TRCODE = 97535 THEN 'PT-UVPM'
	WHEN TRCODE = 97545 THEN 'PT-UVPM'
	WHEN TRCODE = 97750 THEN 'PT-UVPM'
	WHEN TRCODE = 97760 THEN 'PT-UVPM'
	WHEN TRCODE = 99070 THEN 'PT-UVPM'
	WHEN TRCODE = 99080 THEN 'UVPM'
	WHEN TRCODE = 99201 THEN 'Medical-UVPM'
	WHEN TRCODE = 99202 THEN 'Medical-UVPM'
	WHEN TRCODE = 99203 THEN 'Medical-UVPM'
	WHEN TRCODE = 99204 THEN 'Medical-UVPM'
	WHEN TRCODE = 99205 THEN 'Medical-UVPM'
	WHEN TRCODE = 99211 THEN 'Medical-UVPM'
	WHEN TRCODE = 99212 THEN 'Medical-UVPM'
	WHEN TRCODE = 99213 THEN 'Medical-UVPM'
	WHEN TRCODE = 99214 THEN 'Medical-UVPM'
	WHEN TRCODE = 99215 THEN 'Medical-UVPM'
	WHEN TRCODE = 99223 THEN 'Medical-UVPM'
	WHEN TRCODE = 99231 THEN 'Medical-UVPM'
	WHEN TRCODE = 99232 THEN 'Medical-UVPM'
	WHEN TRCODE = 99233 THEN 'Medical-UVPM'
	WHEN TRCODE = 99241 THEN 'Medical-UVPM'
	WHEN TRCODE = 99242 THEN 'Medical-UVPM'
	WHEN TRCODE = 99243 THEN 'Medical-UVPM'
	WHEN TRCODE = 99244 THEN 'Medical-UVPM'
	WHEN TRCODE = 99245 THEN 'Medical-UVPM'
	WHEN TRCODE = 99349 THEN 'Medical-UVPM'
	WHEN TRCODE = 99354 THEN 'Medical-UVPM'
	WHEN TRCODE = 99355 THEN 'Medical-UVPM'
	WHEN TRCODE = 123456 THEN 'UVPM'
	WHEN TRCODE = 988888 THEN 'UVPM'
	WHEN TRCODE = 998877 THEN 'UVPM'
	ELSE 'UVPM'
	END
ELSE LONAME
END as "Specific Location"
,CASE
WHEN #CPU_TRANS_Charges.Entity LIKE 'CV' AND TRLOC = 1 THEN 'CENTRAL VALLEY MED CTR'
WHEN #CPU_TRANS_Charges.Entity LIKE 'CV' AND TRLOC = 2 THEN 'CENTRAL VALLEY MED CTR'
WHEN #CPU_TRANS_Charges.Entity LIKE 'CV' AND TRLOC = 3 THEN 'CENTRAL VALLEY MED CTR'
WHEN #CPU_TRANS_Charges.Entity LIKE 'GV' AND TRLOC = 1 THEN 'GUNNISON VALLEY HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'GV' AND TRLOC = 2 THEN 'GUNNISON VALLEY HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'GV' AND TRLOC = 3 THEN 'GUNNISON VALLEY HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'PM' AND TRLOC = 1 THEN 'UTAH VALLEY PAIN MANAGEMENT'
WHEN #CPU_TRANS_Charges.Entity LIKE 'PM' AND TRLOC = 2 THEN 'UTAH VALLEY PAIN MANAGEMENT'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND TRLOC = 1 THEN 'DIXIE REG. MED. CTR.'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND TRLOC = 2 THEN 'DIXIE REG. MED. CTR.'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND TRLOC = 3 THEN 'DIXIE REG. MED. CTR.'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND TRLOC = 20 THEN 'DIXIE REG. MED. CTR.'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND TRLOC = 21 THEN 'DIXIE REG. MED. CTR.'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SJ' AND TRLOC = 1 THEN 'SAN JUAN HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SJ' AND TRLOC = 2 THEN 'SAN JUAN HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'SJ' AND TRLOC = 3 THEN 'SAN JUAN HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 1 THEN 'UTAH VALLEY REG MED CTR'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 2 THEN 'UTAH VALLEY REG MED CTR'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 3 THEN 'UTAH VALLEY REG MED CTR'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 4 THEN 'OREM COMMUNITY HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 5 THEN 'OREM COMMUNITY HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 6 THEN 'OREM COMMUNITY HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 7 THEN 'AMERICAN FORK HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 8 THEN 'AMERICAN FORK HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 9 THEN 'AMERICAN FORK HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 10 THEN 'CASTLE VIEW HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 11 THEN 'CASTLE VIEW HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 12 THEN 'CASTLE VIEW HOSPITAL'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 22 THEN 'NORTH OREM CLINIC'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 23 THEN 'NORTH OREM CLINIC'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 26 THEN 'HIGHLAND CLINIC'
WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND TRLOC = 27 THEN 'HIGHLAND CLINIC'
ELSE LONAME
END as "Location"
,CASE
WHEN CPU_DOCTR_TRNPCP.DRNAME IS NOT NULL AND LEN(CPU_DOCTR_TRNPCP.DRNAME) > 1
	THEN LEFT(CPU_DOCTR_TRNPCP.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_TRNPCP.DRNAME))
WHEN CPU_DOCTR_TRNPCP.DRNAME IS NOT NULL AND #CPU_TRANS_Charges.TRNPCP <> 0 THEN CPU_DOCTR_TRNPCP.DRNAME
WHEN LEN(CPU_DOCTR_TRADR#.DRNAME) > 1 THEN LEFT(CPU_DOCTR_TRADR#.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_TRADR#.DRNAME))
ELSE CPU_DOCTR_TRADR#.DRNAME
END as "Performing Physician"
,[Referring Physician] as "Referring Physician"
,[Referring Organization]
,[Referring Organization Type]
,[Referring Parent Organization]
,[Referring Medical Group]
,CASE
WHEN CPU_DOCTR_TRNORD.DRNAME IS NOT NULL AND LEN(CPU_DOCTR_TRNPCP.DRNAME) > 1
	THEN LEFT(CPU_DOCTR_TRNPCP.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_TRNPCP.DRNAME))
WHEN CPU_DOCTR_TRNPCP.DRNAME IS NOT NULL AND #CPU_TRANS_Charges.TRNPCP <> 0 THEN CPU_DOCTR_TRNPCP.DRNAME
END as "Supervising Physician"
,NULL as "Referral Source"
,TRAMT as "Charges"
,NULL as "Payments"
,NULL as "Adjustments"
,TRAMT as "Amount"
,NULL as "Payment from Collections"
,NULL as "Amount Written Off"
,NULL as "Self-Pay"
,NULL as "Payment at Time of Service"
,NULL as "Payment on Prior Service"
,CPU_MEMBR.MBSEX as "Gender"
,DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) as "Age"
,CASE
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 10 THEN '0 to 10 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 10 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 20 THEN '10 to 20 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 20 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 30 THEN '20 to 30 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 30 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 40 THEN '30 to 40 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 40 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 50 THEN '40 to 50 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 50 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 60 THEN '50 to 60 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 60 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 70 THEN '60 to 70 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 70 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 80 THEN '70 to 80 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 80 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 90 THEN '80 to 90 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 90 THEN '90+ Years'
END as "Age Bracket"
,NULL as "Language"
,NULL as "Ethnicity"
,SS_Zip2FIPS.STATE as "STATE"
,SS_Zip2FIPS.FIPS as "FIPS"
,SS_Zip2FIPS.ZIP as "ZIP"
,#CPU_TRANS_Charges.Entity as "Entity"
,NULL as "Credit Description"
,NULL AS "Credit Category"
,NULL AS "URB Action"

FROM
#CPU_TRANS_Charges
LEFT JOIN CPU_BS70_CTYPE
ON #CPU_TRANS_Charges.CHTYPE = CPU_BS70_CTYPE.CTCODE AND #CPU_TRANS_Charges.CHSUBT = CPU_BS70_CTYPE.CTSUBT
LEFT JOIN SS_CPU_InsuranceToFinancialClass
ON #CPU_TRANS_Charges.TIIN#1 = InsuranceNumber
LEFT JOIN CPU_LOC
ON #CPU_TRANS_Charges.TRLOC = CPU_LOC.LONUM AND #CPU_TRANS_Charges.Entity LIKE CPU_LOC.Entity
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_TRADR#"
ON #CPU_TRANS_Charges.TRADR# = CPU_DOCTR_TRADR#.DRNUM AND #CPU_TRANS_Charges.Entity LIKE CPU_DOCTR_TRADR#.Entity
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_TRNORD"
ON #CPU_TRANS_Charges.TRNORD = CPU_DOCTR_TRNORD.DRNUM AND #CPU_TRANS_Charges.Entity LIKE 'PM' AND CPU_DOCTR_TRNORD.Entity LIKE 'PM'
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_TRNPCP"
ON #CPU_TRANS_Charges.TRNPCP = CPU_DOCTR_TRNPCP.DRNUM AND #CPU_TRANS_Charges.Entity LIKE 'PM' AND CPU_DOCTR_TRNPCP.Entity LIKE 'PM'
LEFT JOIN CPU_FAMLY
ON #CPU_TRANS_Charges.TRFAM# = CPU_FAMLY.FMNUM AND #CPU_TRANS_Charges.Entity LIKE CPU_FAMLY.Entity
LEFT JOIN CPU_MEMBR
ON #CPU_TRANS_Charges.TRFAM# = CPU_MEMBR.MBFAM# AND #CPU_TRANS_Charges.Entity LIKE CPU_MEMBR.Entity
LEFT JOIN SS_Zip2FIPS
ON CPU_FAMLY.FMZIP1 LIKE SS_Zip2FIPS.ZIP_String

UNION ALL

SELECT
CASE
WHEN DETTYPE LIKE 'P' THEN 'Payments'
ELSE 'Adjustments'
END as "Type"
,DETFAM# as "Account Number"
,CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0
THEN #CPU_TRANS_Charges.CHMCD1
END as "CPT Code"
,#CPU_TRANS_Charges.TRMODF + '' + #CPU_TRANS_Charges.TRMOD2 + ' ' + #CPU_TRANS_Charges.TRMOD3 as "Modifiers"
,#CPU_TRANS_Charges.CHDESC as "Description"
,CPU_BS70_CTYPE.CTDESC as "Category"
,CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0
THEN #CPU_TRANS_Charges.TRDIAG+' '+#CPU_TRANS_Charges.TRDIG2+' '+#CPU_TRANS_Charges.TRDIG3+' '+#CPU_TRANS_Charges.TRDIG4
ELSE #CPU_TRANS_Credits.TRDIG2+' '+#CPU_TRANS_Credits.TRDIG3+' '+#CPU_TRANS_Credits.TRDIG4
END as "Diagnosis Codes"
,#CPU_TRANS_Credits.TRPDAT as "Date of Entry"
,ISNULL(#CPU_TRANS_Charges.TRPDAT, #CPU_TRANS_Credits.TRPDAT) as "Date of Charge"
,CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0
THEN #CPU_TRANS_Charges.TRTDAT
ELSE #CPU_TRANS_Credits.TRTDAT
END as "Date of Service"
,CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN CreditInsurance.InsuranceName
ELSE CreditInsurance.InsuranceName
END as "Insurance"
,CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN ISNULL(ChargeInsurance.FinancialClass, 'Unknown')
ELSE ISNULL(CreditInsurance.FinancialClass, 'Unknown')
END as "Financial Class"
,CreditInsurance.InsuranceName as "Insurance of Specific Transaction"
,ISNULL(CreditInsurance.FinancialClass, 'Unknown') as "Financial Class of Specific Transaction"
,CASE
WHEN #CPU_TRANS_Charges.Entity LIKE 'PM' AND #CPU_TRANS_Charges.TRLOC = 1
THEN CASE
	WHEN #CPU_TRANS_Charges.TRCODE = 411 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 430 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 431 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 434 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 518 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 585 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 600 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 621 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 631 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 666 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 700 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 777 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 800 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 900 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 950 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 999 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 1100 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 1101 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 1845 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 1885 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 3288 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 3807 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 3908 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 3915 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 4595 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 6040 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 6666 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 7335 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8427 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8431 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8510 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8539 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8540 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8542 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8553 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8730 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8978 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8979 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8980 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8981 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8982 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8983 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8984 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8985 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8986 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8987 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8988 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8989 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8990 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8991 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 8992 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 9070 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 9907 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 9981 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 9988 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 9998 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 9999 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 20550 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 20551 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 20552 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 20553 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 20605 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 20610 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64405 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64450 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64505 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64550 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64612 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64613 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64614 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64615 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64616 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 64999 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 77002 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 80101 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 80104 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 80301 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 81003 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 82055 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 82570 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 83986 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 84311 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 85610 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90785 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90791 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90792 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90801 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90804 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90806 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90808 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90832 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90834 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90837 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90839 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90847 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90853 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90875 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90876 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 90901 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95860 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95861 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95863 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95867 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95869 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95870 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95874 THEN 'Botox (Medical)-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95885 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95886 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95887 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95888 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95900 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95903 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95904 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95907 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95908 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95909 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95910 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95911 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95912 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95913 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95933 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95934 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95936 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95937 THEN 'EMG-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95970 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95972 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 95973 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 96101 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 96103 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 96118 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 96152 THEN 'Psych-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 96372 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 96999 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97001 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97002 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97012 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97014 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97033 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97035 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97110 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97112 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97116 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97124 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97140 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97530 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97535 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97545 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97750 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 97760 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99070 THEN 'PT-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99080 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99201 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99202 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99203 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99204 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99205 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99211 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99212 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99213 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99214 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99215 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99223 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99231 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99232 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99233 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99241 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99242 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99243 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99244 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99245 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99349 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99354 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 99355 THEN 'Medical-UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 123456 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 988888 THEN 'UVPM'
	WHEN #CPU_TRANS_Charges.TRCODE = 998877 THEN 'UVPM'
	ELSE 'UVPM'
	END
ELSE LONAME
END as "Specific Location"
,CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN CASE
	WHEN #CPU_TRANS_Charges.Entity LIKE 'CV' AND #CPU_TRANS_Charges.TRLOC = 1 THEN 'CENTRAL VALLEY MED CTR'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'CV' AND #CPU_TRANS_Charges.TRLOC = 2 THEN 'CENTRAL VALLEY MED CTR'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'CV' AND #CPU_TRANS_Charges.TRLOC = 3 THEN 'CENTRAL VALLEY MED CTR'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'GV' AND #CPU_TRANS_Charges.TRLOC = 1 THEN 'GUNNISON VALLEY HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'GV' AND #CPU_TRANS_Charges.TRLOC = 2 THEN 'GUNNISON VALLEY HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'GV' AND #CPU_TRANS_Charges.TRLOC = 3 THEN 'GUNNISON VALLEY HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'PM' AND #CPU_TRANS_Charges.TRLOC = 1 THEN 'UTAH VALLEY PAIN MANAGEMENT'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'PM' AND #CPU_TRANS_Charges.TRLOC = 2 THEN 'UTAH VALLEY PAIN MANAGEMENT'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND #CPU_TRANS_Charges.TRLOC = 1 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND #CPU_TRANS_Charges.TRLOC = 2 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND #CPU_TRANS_Charges.TRLOC = 3 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND #CPU_TRANS_Charges.TRLOC = 20 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SG' AND #CPU_TRANS_Charges.TRLOC = 21 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SJ' AND #CPU_TRANS_Charges.TRLOC = 1 THEN 'SAN JUAN HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SJ' AND #CPU_TRANS_Charges.TRLOC = 2 THEN 'SAN JUAN HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'SJ' AND #CPU_TRANS_Charges.TRLOC = 3 THEN 'SAN JUAN HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 1 THEN 'UTAH VALLEY REG MED CTR'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 2 THEN 'UTAH VALLEY REG MED CTR'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 3 THEN 'UTAH VALLEY REG MED CTR'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 4 THEN 'OREM COMMUNITY HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 5 THEN 'OREM COMMUNITY HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 6 THEN 'OREM COMMUNITY HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 7 THEN 'AMERICAN FORK HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 8 THEN 'AMERICAN FORK HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 9 THEN 'AMERICAN FORK HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 10 THEN 'CASTLE VIEW HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 11 THEN 'CASTLE VIEW HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 12 THEN 'CASTLE VIEW HOSPITAL'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 22 THEN 'NORTH OREM CLINIC'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 23 THEN 'NORTH OREM CLINIC'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 26 THEN 'HIGHLAND CLINIC'
	WHEN #CPU_TRANS_Charges.Entity LIKE 'UVR' AND #CPU_TRANS_Charges.TRLOC = 27 THEN 'HIGHLAND CLINIC'
	ELSE LONAME
	END
ELSE
	CASE
	WHEN #CPU_TRANS_Credits.Entity LIKE 'CV' AND #CPU_TRANS_Credits.TRLOC = 1 THEN 'CENTRAL VALLEY MED CTR'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'CV' AND #CPU_TRANS_Credits.TRLOC = 2 THEN 'CENTRAL VALLEY MED CTR'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'CV' AND #CPU_TRANS_Credits.TRLOC = 3 THEN 'CENTRAL VALLEY MED CTR'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'GV' AND #CPU_TRANS_Credits.TRLOC = 1 THEN 'GUNNISON VALLEY HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'GV' AND #CPU_TRANS_Credits.TRLOC = 2 THEN 'GUNNISON VALLEY HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'GV' AND #CPU_TRANS_Credits.TRLOC = 3 THEN 'GUNNISON VALLEY HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'PM' AND #CPU_TRANS_Credits.TRLOC = 1 THEN 'UTAH VALLEY PAIN MANAGEMENT'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'PM' AND #CPU_TRANS_Credits.TRLOC = 2 THEN 'UTAH VALLEY PAIN MANAGEMENT'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SG' AND #CPU_TRANS_Credits.TRLOC = 1 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SG' AND #CPU_TRANS_Credits.TRLOC = 2 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SG' AND #CPU_TRANS_Credits.TRLOC = 3 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SG' AND #CPU_TRANS_Credits.TRLOC = 20 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SG' AND #CPU_TRANS_Credits.TRLOC = 21 THEN 'DIXIE REG. MED. CTR.'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SJ' AND #CPU_TRANS_Credits.TRLOC = 1 THEN 'SAN JUAN HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SJ' AND #CPU_TRANS_Credits.TRLOC = 2 THEN 'SAN JUAN HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'SJ' AND #CPU_TRANS_Credits.TRLOC = 3 THEN 'SAN JUAN HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 1 THEN 'UTAH VALLEY REG MED CTR'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 2 THEN 'UTAH VALLEY REG MED CTR'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 3 THEN 'UTAH VALLEY REG MED CTR'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 4 THEN 'OREM COMMUNITY HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 5 THEN 'OREM COMMUNITY HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 6 THEN 'OREM COMMUNITY HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 7 THEN 'AMERICAN FORK HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 8 THEN 'AMERICAN FORK HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 9 THEN 'AMERICAN FORK HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 10 THEN 'CASTLE VIEW HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 11 THEN 'CASTLE VIEW HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 12 THEN 'CASTLE VIEW HOSPITAL'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 22 THEN 'NORTH OREM CLINIC'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 23 THEN 'NORTH OREM CLINIC'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 26 THEN 'HIGHLAND CLINIC'
	WHEN #CPU_TRANS_Credits.Entity LIKE 'UVR' AND #CPU_TRANS_Credits.TRLOC = 27 THEN 'HIGHLAND CLINIC'
	ELSE LONAME
	END
END as "Location"
,CASE
WHEN CPU_DOCTR_TRNPCP.DRNAME IS NOT NULL AND LEN(CPU_DOCTR_TRNPCP.DRNAME) > 1
	THEN LEFT(CPU_DOCTR_TRNPCP.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_TRNPCP.DRNAME))
WHEN CPU_DOCTR_TRNPCP.DRNAME IS NOT NULL AND #CPU_TRANS_Charges.TRNPCP <> 0 THEN CPU_DOCTR_TRNPCP.DRNAME
WHEN LEN(CPU_DOCTR_TRADR#.DRNAME) > 1 THEN LEFT(CPU_DOCTR_TRADR#.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_TRADR#.DRNAME))
ELSE CPU_DOCTR_TRADR#.DRNAME
END as "Performing Physician"
,[Referring Physician] as "Referring Physician"
,[Referring Organization]
,[Referring Organization Type]
,[Referring Parent Organization]
,[Referring Medical Group]
,CASE
WHEN CPU_DOCTR_TRNORD.DRNAME IS NOT NULL AND LEN(CPU_DOCTR_TRNORD.DRNAME) > 1
	THEN LEFT(CPU_DOCTR_TRNORD.DRNAME, PATINDEX('%[^,] %', CPU_DOCTR_TRNORD.DRNAME))
WHEN CPU_DOCTR_TRNORD.DRNAME IS NOT NULL AND #CPU_TRANS_Charges.TRNORD <> 0 THEN CPU_DOCTR_TRNORD.DRNAME
END as "Supervising Physician"
,NULL as "Referral Source"
,NULL as "Charges"
,CASE
WHEN CPU_DETAIL.DETTYPE LIKE 'P'
THEN -1*DETAPAMT
END as "Payments"
,CASE
WHEN CPU_DETAIL.DETTYPE LIKE 'A'
THEN -1*DETAPAMT
END as "Adjustments"
,DETAPAMT as "Amount"
,CASE
WHEN #CPU_TRANS_Credits.TRCODE = 21 THEN -1*DETAPAMT
END as "Payment from Collections"
,CASE
WHEN #CPU_TRANS_Credits.TRCODE = 130 THEN -1*DETAPAMT
END as "Amount Written Off"
,CASE
WHEN #CPU_TRANS_Credits.TRCODE = 1 OR #CPU_TRANS_Credits.TRCODE = 111 OR #CPU_TRANS_Credits.TRCODE = 112 THEN -1*DETAPAMT
END as "Self-Pay"
,CASE
WHEN #CPU_TRANS_Credits.TRCODE = 111 THEN -1*DETAPAMT
END as "Payment at Time of Service"
,CASE
WHEN #CPU_TRANS_Credits.TRCODE = 112 THEN -1*DETAPAMT
END as "Payment on Prior Service"
,CPU_MEMBR.MBSEX as "Gender"
,DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) as "Age"
,CASE
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 10 THEN '0 to 10 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 10 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 20 THEN '10 to 20 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 20 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 30 THEN '20 to 30 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 30 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 40 THEN '30 to 40 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 40 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 50 THEN '40 to 50 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 50 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 60 THEN '50 to 60 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 60 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 70 THEN '60 to 70 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 70 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 80 THEN '70 to 80 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 80 AND DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) <= 90 THEN '80 to 90 Years'
WHEN DATEDIFF(year, CPU_MEMBR.MBDOB, #CPU_TRANS_Charges.TRTDAT) > 90 THEN '90+ Years'
END as "Age Bracket"
,NULL as "Language"
,NULL as "Ethnicity"
,SS_Zip2FIPS.STATE as "STATE"
,SS_Zip2FIPS.FIPS as "FIPS"
,SS_Zip2FIPS.ZIP as "ZIP"
,CPU_DETAIL.Entity as "Entity"
,CREDIT_TYPES.CREDIT_DESC as "Credit Description"
,CREDIT_TYPES.CREDIT_CATEGORY AS "Credit Category"
,CREDIT_TYPES.URB_ACTION AS "URB Action"

FROM
CPU_DETAIL
LEFT JOIN #CPU_TRANS_Charges
ON CPU_DETAIL.DETFAM# = #CPU_TRANS_Charges.TRFAM#
	AND CPU_DETAIL.DETCHGSEQ = #CPU_TRANS_Charges.TRSEQ#
	AND CPU_DETAIL.Entity LIKE #CPU_TRANS_Charges.Entity
LEFT JOIN CPU_TRANS as #CPU_TRANS_Credits
ON CPU_DETAIL.DETFAM# = #CPU_TRANS_Credits.TRFAM#
	AND CPU_DETAIL.DETCRDSEQ = #CPU_TRANS_Credits.TRSEQ#
	AND CPU_DETAIL.Entity LIKE #CPU_TRANS_Credits.Entity
LEFT JOIN CPU_BS70_CTYPE
ON #CPU_TRANS_Charges.CHTYPE = CPU_BS70_CTYPE.CTCODE AND #CPU_TRANS_Charges.CHSUBT = CPU_BS70_CTYPE.CTSUBT
LEFT JOIN SS_CPU_InsuranceToFinancialClass as "ChargeInsurance"
ON #CPU_TRANS_Charges.TIIN#1 = ChargeInsurance.InsuranceNumber
LEFT JOIN SS_CPU_InsuranceToFinancialClass as "CreditInsurance"
ON #CPU_TRANS_Credits.TRINSC = CreditInsurance.InsuranceNumber
LEFT JOIN CPU_LOC
ON CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN #CPU_TRANS_Charges.TRLOC
ELSE #CPU_TRANS_Credits.TRLOC
END = CPU_LOC.LONUM
AND #CPU_TRANS_Charges.Entity LIKE CPU_LOC.Entity
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_TRADR#"
ON CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN #CPU_TRANS_Charges.TRADR#
ELSE #CPU_TRANS_Credits.TRADR# 
END = CPU_DOCTR_TRADR#.DRNUM AND #CPU_TRANS_Charges.Entity LIKE CPU_DOCTR_TRADR#.Entity
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_TRNORD"
ON CPU_DETAIL.Entity LIKE 'PM' AND CPU_DOCTR_TRNORD.Entity LIKE 'PM' AND
CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN #CPU_TRANS_Charges.TRNORD
END = CPU_DOCTR_TRNORD.DRNUM
LEFT JOIN CPU_DOCTR as "CPU_DOCTR_TRNPCP"
ON CPU_DETAIL.Entity LIKE 'PM' AND CPU_DOCTR_TRNPCP.Entity LIKE 'PM' AND
CASE
WHEN CPU_DETAIL.DETCHGSEQ <> 0 THEN #CPU_TRANS_Charges.TRNORD
END = CPU_DOCTR_TRNPCP.DRNUM
LEFT JOIN CPU_FAMLY
ON CPU_DETAIL.DETFAM# = CPU_FAMLY.FMNUM AND CPU_DETAIL.Entity LIKE CPU_FAMLY.Entity
LEFT JOIN CPU_MEMBR
ON CPU_DETAIL.DETFAM# = CPU_MEMBR.MBFAM# AND CPU_DETAIL.Entity LIKE CPU_MEMBR.Entity
LEFT JOIN SS_Zip2FIPS
ON CPU_FAMLY.FMZIP1 LIKE SS_Zip2FIPS.ZIP_String
LEFT JOIN CREDIT_TYPES
ON CREDIT_TYPES.[SOURCE] LIKE 'CPU' AND #CPU_TRANS_Credits.TRCODE = CREDIT_TYPES.KEY_NUM


WHERE (DETTYPE LIKE 'P' OR DETTYPE LIKE 'A')
--AND #CPU_TRANS_Credits.TRMODF NOT LIKE '*P'


UNION ALL


SELECT
'Charges' as "Type" 
,IVC_PatientProfile.PatientProfileId as "Account Number"
,ISNULL(IVC_PatientVisitProcs.CPTCode, IVC_PatientVisitProcs.Code) as "CPT Code"
,LEFT(Modifier1.Description, 2) + ' ' + LEFT(Modifier2.Description, 2) + ' ' + LEFT(Modifier3.Description, 2) + ' ' + LEFT(Modifier4.Description, 2) as "Modifiers"
,IVC_PatientVisitProcs.Description as "Description"
,CASE
WHEN IVC_PatientVisitProcs.Code LIKE '36475' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '36476' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '36478' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '36479' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '37765' THEN 'Phlebectomy'
WHEN IVC_PatientVisitProcs.Code LIKE '37766' THEN 'Phlebectomy'
WHEN IVC_PatientVisitProcs.Code LIKE '37799' THEN 'Phlebectomy'
WHEN IVC_PatientVisitProcs.Code LIKE '36470' THEN 'Sclerotherapy'
WHEN IVC_PatientVisitProcs.Code LIKE '36471' THEN 'Sclerotherapy'
WHEN IVC_PatientVisitProcs.Code LIKE '99201' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99202' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99203' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99204' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99205' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99211' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99212' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99213' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99214' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99215' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '10022' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '19000' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '19100' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '19285' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '27094' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '60001' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76376' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76536' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76604' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76645' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76536' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76700' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76705' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76770' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76775' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76801' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76802' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76805' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76810' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76815' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76816' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76817' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76818' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76819' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76830' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76831' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76856' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76857' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76870' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76881' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76882' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76937' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '77001' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93000' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93306' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93307' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93351' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93880' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93882' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93922' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93923' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93924' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93925' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93926' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93930' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93931' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93965' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93970' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93971' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93975' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93978' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93979' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93990' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE 'G0389' THEN 'Ultrasound'
ELSE 'Other IVC'
END as "Category"
,Diags1.ICD9Code + ' ' + Diags2.ICD9Code + ' ' + Diags3.ICD9Code + ' ' + Diags4.ICD9Code + ' ' + Diags5.ICD9Code + ' ' + Diags6.ICD9Code + ' ' + Diags7.ICD9Code + ' ' + Diags8.ICD9Code + ' ' + Diags9.ICD9Code + ' ' +  Diags10.ICD9Code + ' ' + Diags11.ICD9Code + ' ' + Diags12.ICD9Code as "Diagnosis Codes"
,IVC_PatientVisitProcs.DateOfEntry as "Date of Entry"
,IVC_PatientVisitProcs.DateOfEntry as "Date of Charge"
,IVC_PatientVisitProcs.DateOfServiceFrom as "Date of Service"
,InsuranceName as "Insurance"
,ISNULL(FinancialClass, 'Unknown') as "Financial Class"
,InsuranceName as "Insurance of Specific Transaction"
,ISNULL(FinancialClass, 'Unknown') as "Financial Class of Specific Transaction"
,Facility.ListName as "Specific Location"
,Facility.OrgName as "Location"
,PerformingDoctor.ListName as "Performing Physician"
,CASE
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 27		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 17		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 26		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 23		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 24		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 415		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 25		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 1328		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 28		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 745		THEN 'Unknown'
	WHEN ReferralSource.Description like 'Physician Referral'					THEN ISNULL(ReferringDoctor.ListName, 'Unknown')
END as "Referring Physician"
,TaskAccount.NAME as "Referring Organization"
,TaskAccount.LKL3__Practice_Type__c as "Referring Organization Type"
,ISNULL(ParentAccount.NAME, TaskAccount.NAME) as "Referring Parent Organization"
,TaskAccount.GROUP__C as "Referring Medical Group"
,NULL as "Supervising Physician"
,ReferralSource.Description as "Referral Source"
,IVC_PatientVisitProcs.TotalFee as "Charges"
,NULL as "Payments"
,NULL as "Adjustments"
,IVC_PatientVisitProcs.TotalFee as "Amount"
,NULL as "Payment from Collections"
,NULL as "Amount Written Off"
,NULL as "Self-Pay"
,NULL as "Payment at Time of Service"
,NULL as "Payment on Prior Service"
,IVC_PatientProfile.Sex as "Gender"
,DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) as "Age"
,CASE
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 10 THEN '0 to 10 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 10 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 20 THEN '10 to 20 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 20 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 30 THEN '20 to 30 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 30 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 40 THEN '30 to 40 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 40 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 50 THEN '40 to 50 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 50 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 60 THEN '50 to 60 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 60 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 70 THEN '60 to 70 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 70 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 80 THEN '70 to 80 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 80 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 90 THEN '80 to 90 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 90 THEN '90+ Years'
END as "Age Bracket"
,IVC_Language.ShortDescription as "Language"
,Ethnicity.Description as "Ethnicity"
,SS_Zip2FIPS.STATE as "STATE"
,SS_Zip2FIPS.FIPS as "FIPS"
,SS_Zip2FIPS.ZIP as "ZIP"
,CASE
WHEN IVC_PatientVisit.CompanyId = 4 THEN 'IVC'
ELSE 'UVU'
END as "Entity"
,NULL as "Credit Description"
,NULL AS "Credit Category"
,NULL AS "URB Action"

FROM
IVC_PatientVisitProcs
LEFT JOIN IVC_PatientVisit
ON IVC_PatientVisitProcs.PatientVisitId = IVC_PatientVisit.PatientVisitId
LEFT JOIN IVC_DoctorFacility as "Facility"
ON IVC_PatientVisit.FacilityId = Facility.DoctorFacilityId
LEFT JOIN SS_IVC_InsuranceToFinancialClass
ON IVC_PatientVisit.CurrentInsuranceCarriersId = SS_IVC_InsuranceToFinancialClass.InsuranceNumber
LEFT JOIN IVC_PatientProfile
ON IVC_PatientVisit.PatientProfileId = IVC_PatientProfile.PatientProfileId
LEFT JOIN SS_Zip2FIPS
ON CASE
WHEN ISNUMERIC(LEFT(IVC_PatientProfile.Zip,5)) = 1  THEN LEFT(IVC_PatientProfile.Zip,5)
END LIKE SS_Zip2FIPS.ZIP_String
LEFT JOIN IVC_PatientVisitDiags as "Diags1"
ON IVC_PatientVisit.PatientVisitId = Diags1.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags1 = Diags1.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags2"
ON IVC_PatientVisit.PatientVisitId = Diags2.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags2 = Diags2.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags3"
ON IVC_PatientVisit.PatientVisitId = Diags3.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags3 = Diags3.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags4"
ON IVC_PatientVisit.PatientVisitId = Diags4.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags4 = Diags4.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags5"
ON IVC_PatientVisit.PatientVisitId = Diags5.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags5 = Diags5.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags6"
ON IVC_PatientVisit.PatientVisitId = Diags6.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags6 = Diags6.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags7"
ON IVC_PatientVisit.PatientVisitId = Diags7.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags7 = Diags7.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags8"
ON IVC_PatientVisit.PatientVisitId = Diags8.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags8 = Diags8.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags9"
ON IVC_PatientVisit.PatientVisitId = Diags9.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags9 = Diags9.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags10"
ON IVC_PatientVisit.PatientVisitId = Diags10.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags10 = Diags10.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags11"
ON IVC_PatientVisit.PatientVisitId = Diags11.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags11 = Diags11.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags12"
ON IVC_PatientVisit.PatientVisitId = Diags12.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags12 = Diags12.ListOrder
LEFT JOIN IVC_Language
ON IVC_PatientProfile.LanguageId = IVC_Language.LanguageId
LEFT JOIN IVC_MedLists as "ReferralSource"
ON IVC_PatientProfile.ReferenceSourceMId = ReferralSource.MedListsId
LEFT JOIN IVC_DoctorFacility as "ReferringDoctor"
ON IVC_PatientVisit.ReferringDoctorId = ReferringDoctor.DoctorFacilityId
LEFT JOIN IVC_MedLists as "Modifier1"
ON Modifier1MId = Modifier1.MedListsId
LEFT JOIN IVC_MedLists as "Modifier2"
ON Modifier2MId = Modifier2.MedListsId
LEFT JOIN IVC_MedLists as "Modifier3"
ON Modifier3MId = Modifier3.MedListsId
LEFT JOIN IVC_MedLists as "Modifier4"
ON Modifier4MId = Modifier4.MedListsId
LEFT JOIN IVC_DoctorFacility as "PerformingDoctor"
ON IVC_PatientVisit.DoctorId = PerformingDoctor.DoctorFacilityId
LEFT JOIN IVC_MedLists as "Ethnicity"
ON IVC_PatientProfile.EthnicityMId = Ethnicity.MedListsId
LEFT JOIN ZZ_Contact
ON ReferringDoctor.NPI LIKE ZZ_Contact.LKL3__NPI__C
AND NOT (
	IVC_PatientVisit.ReferringDoctorId = 27
	OR IVC_PatientVisit.ReferringDoctorId = 17
	OR IVC_PatientVisit.ReferringDoctorId = 26
	OR IVC_PatientVisit.ReferringDoctorId = 23
	OR IVC_PatientVisit.ReferringDoctorId = 24
	OR IVC_PatientVisit.ReferringDoctorId = 415
	OR IVC_PatientVisit.ReferringDoctorId = 25
	OR IVC_PatientVisit.ReferringDoctorId = 1328
	OR IVC_PatientVisit.ReferringDoctorId = 28
	OR IVC_PatientVisit.ReferringDoctorId = 745
)
AND NOT ZZ_Contact.LKL3__NPI__C = ''
LEFT JOIN ZZ_Account as TaskAccount
ON ZZ_Contact.ACCOUNTID LIKE TaskAccount.ID
LEFT JOIN ZZ_Account as ParentAccount
ON TaskAccount.PARENTID LIKE ParentAccount.ID

WHERE IVC_PatientVisit.CompanyId <> 3

UNION ALL

SELECT
CASE
WHEN IVC_Transactions.Action LIKE 'P' THEN 'Payments'
ELSE 'Adjustments'
END as "Type"
,IVC_PatientVisit.PatientProfileId as "Account Number"
,ISNULL(IVC_PatientVisitProcs.CPTCode, IVC_PatientVisitProcs.Code) as "CPT Code"
,LEFT(Modifier1.Description, 2) + ' ' + LEFT(Modifier2.Description, 2) + ' ' + LEFT(Modifier3.Description, 2) + ' ' + LEFT(Modifier4.Description, 2) as "Modifiers"
,IVC_PatientVisitProcs.Description as "Description"
,CASE
WHEN IVC_PatientVisitProcs.Code LIKE '36475' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '36476' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '36478' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '36479' THEN 'Ablation'
WHEN IVC_PatientVisitProcs.Code LIKE '37765' THEN 'Phlebectomy'
WHEN IVC_PatientVisitProcs.Code LIKE '37766' THEN 'Phlebectomy'
WHEN IVC_PatientVisitProcs.Code LIKE '37799' THEN 'Phlebectomy'
WHEN IVC_PatientVisitProcs.Code LIKE '36470' THEN 'Sclerotherapy'
WHEN IVC_PatientVisitProcs.Code LIKE '36471' THEN 'Sclerotherapy'
WHEN IVC_PatientVisitProcs.Code LIKE '99201' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99202' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99203' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99204' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99205' THEN 'New Patient Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99211' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99212' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99213' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99214' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '99215' THEN 'Follow-up Exam'
WHEN IVC_PatientVisitProcs.Code LIKE '10022' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '19000' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '19100' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '19285' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '27094' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '60001' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76376' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76536' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76604' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76645' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76536' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76700' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76705' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76770' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76775' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76801' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76802' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76805' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76810' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76815' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76816' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76817' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76818' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76819' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76830' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76831' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76856' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76857' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76870' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76881' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76882' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '76937' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '77001' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93000' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93306' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93307' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93351' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93880' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93882' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93922' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93923' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93924' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93925' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93926' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93930' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93931' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93965' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93970' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93971' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93975' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93978' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93979' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE '93990' THEN 'Ultrasound'
WHEN IVC_PatientVisitProcs.Code LIKE 'G0389' THEN 'Ultrasound'
ELSE 'Other IVC'
END as "Category"
,Diags1.ICD9Code + ' ' + Diags2.ICD9Code + ' ' + Diags3.ICD9Code + ' ' + Diags4.ICD9Code + ' ' + Diags5.ICD9Code + ' ' + Diags6.ICD9Code + ' ' + Diags7.ICD9Code + ' ' + Diags8.ICD9Code + ' ' + Diags9.ICD9Code + ' ' +  Diags10.ICD9Code + ' ' + Diags11.ICD9Code + ' ' + Diags12.ICD9Code as "Diagnosis Codes"
,IVC_PaymentMethod.DateOfEntry as "Date of Entry"
,IVC_PatientVisitProcs.DateOfEntry as "Date of Charge"
,IVC_PatientVisitProcs.DateOfServiceFrom as "Date of Service"
,Insurance.InsuranceName as "Insurance"
,Insurance.FinancialClass as "Financial Class"
,CASE
WHEN IVC_PaymentMethod.Source = 2 THEN SpecificInsurance.InsuranceName
ELSE 'SELF PAY'
END as "Insurance of Specific Transaction"
,CASE
WHEN IVC_PaymentMethod.Source = 2 THEN SpecificInsurance.FinancialClass
ELSE 'SELF PAY'
END as "Financial Class of Specific Transaction"
,Facility.ListName as "Specific Location"
,Facility.OrgName as "Location"
,PerformingDoctor.ListName as "Performing Physician"
,CASE
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 27			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 17			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 26			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 23			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 24			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 415		THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 25			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 1328		THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 28			THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral' AND IVC_PatientVisit.ReferringDoctorId = 745		THEN 'Unknown'
	WHEN IVC_MedLists.Description like 'Physician Referral'					THEN ISNULL(ReferringDoctor.ListName, 'Unknown')
	ELSE NULL
END as "Referring Physician"
,TaskAccount.NAME as "Referring Organization"
,TaskAccount.LKL3__Practice_Type__c as "Referring Organization Type"
,ISNULL(ParentAccount.NAME, TaskAccount.NAME) as "Referring Parent Organization"
,TaskAccount.GROUP__C as "Referring Medical Group"
,NULL as "Supervising Physician"
,IVC_MedLists.Description as "Referral Source"
,NULL as "Charges"
,CASE
WHEN IVC_Transactions.Action LIKE 'P' THEN IVC_Transactions.Amount
END  as "Payments"
,CASE
WHEN IVC_Transactions.Action LIKE 'A' THEN IVC_Transactions.Amount
END as "Adjustments"
,-1*IVC_Transactions.Amount as "Amount"
,CASE
WHEN IVC_PaymentMethod.PayerId = 357 AND IVC_Transactions.Action LIKE 'P' THEN IVC_Transactions.Amount
END as "Payment from Collections"
,CASE
WHEN IVC_Transactions.ActionTypeMId = 301 AND IVC_Transactions.Action LIKE 'A' THEN IVC_Transactions.Amount
END as "Amount Written Off"
,CASE
WHEN IVC_PaymentMethod.Source = 1 THEN IVC_Transactions.Amount
END as "Self-Pay"
,CASE
WHEN IVC_Transactions.Action LIKE 'P' AND IVC_PaymentMethod.Source = 1 AND IVC_PatientVisitProcs.DateOfServiceFrom = IVC_PaymentMethod.DateOfEntry THEN IVC_Transactions.Amount
END as "Payment at Time of Service"
,CASE
WHEN IVC_Transactions.Action LIKE 'P' AND IVC_PaymentMethod.Source = 1 AND IVC_PatientVisitProcs.DateOfServiceFrom < IVC_PaymentMethod.DateOfEntry AND Visit.Visit IS NOT NULL THEN IVC_Transactions.Amount
END as "Payment on Prior Service"
,IVC_PatientProfile.Sex as "Gender"
,DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) as "Age"
,CASE
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 10 THEN '0 to 10 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 10 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 20 THEN '10 to 20 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 20 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 30 THEN '20 to 30 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 30 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 40 THEN '30 to 40 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 40 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 50 THEN '40 to 50 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 50 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 60 THEN '50 to 60 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 60 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 70 THEN '60 to 70 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 70 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 80 THEN '70 to 80 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 80 AND DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) <= 90 THEN '80 to 90 Years'
WHEN DATEDIFF(year, IVC_PatientProfile.Birthdate, IVC_PatientVisitProcs.DateOfServiceFrom) > 90 THEN '90+ Years'
END as "Age Bracket"
,IVC_Language.ShortDescription as "Language"
,Ethnicity.Description as "Ethnicity"
,SS_Zip2FIPS.STATE as "STATE"
,SS_Zip2FIPS.FIPS as "FIPS"
,SS_Zip2FIPS.ZIP as "ZIP"
,CASE
WHEN IVC_PatientVisit.CompanyId = 4 THEN 'IVC'
ELSE 'UVU'
END as "Entity"
,CREDIT_TYPES.CREDIT_DESC as "Credit Description"
,CASE
WHEN CREDIT_TYPES.KEY_NUM = 304 AND IVC_PaymentMethod.[Source] = 1 AND IVC_PatientVisitProcs.DateOfServiceFrom < IVC_PaymentMethod.DateOfEntry AND Visit.Visit IS NOT NULL THEN 'Payment for Prior Service'
WHEN CREDIT_TYPES.KEY_NUM = 304 AND IVC_PaymentMethod.[Source] = 1 AND IVC_PatientVisitProcs.DateOfServiceFrom = IVC_PaymentMethod.DateOfEntry THEN 'Payment at Time of Service'
WHEN CREDIT_TYPES.KEY_NUM = 304 AND IVC_PaymentMethod.[Source] = 1 THEN 'Patient'
WHEN CREDIT_TYPES.KEY_NUM = 304  AND IVC_Paymentmethod.PayerId = 357 THEN 'Collections'
WHEN CREDIT_TYPES.KEY_NUM = 304 THEN 'Insurance'
WHEN CREDIT_TYPES.KEY_NUM = 306 AND IVC_PaymentMethod.[Source] = 1 THEN 'Patient'
WHEN CREDIT_TYPES.KEY_NUM = 306 THEN 'Insurance'
ELSE CREDIT_TYPES.CREDIT_CATEGORY
END AS "Credit Category"
,CREDIT_TYPES.URB_ACTION AS "URB Action"

FROM
IVC_Transactions
LEFT JOIN IVC_VisitTransactions
ON IVC_Transactions.VisitTransactionsId = IVC_VisitTransactions.VisitTransactionsId
LEFT JOIN IVC_PaymentMethod
ON IVC_VisitTransactions.PaymentMethodId = IVC_PaymentMethod.PaymentMethodId
LEFT JOIN SS_IVC_InsuranceToFinancialClass as "SpecificInsurance"
ON IVC_VisitTransactions.PaymentMethodId = SpecificInsurance.InsuranceNumber
LEFT JOIN IVC_PatientVisit
ON IVC_VisitTransactions.PatientVisitid = IVC_PatientVisit.PatientVisitId
LEFT JOIN IVC_DoctorFacility as "Facility"
ON IVC_PatientVisit.FacilityId = Facility.DoctorFacilityId
LEFT JOIN IVC_PatientVisitProcs
ON IVC_PatientVisit.PatientVisitId = IVC_PatientVisitProcs.PatientVisitId AND IVC_PatientVisitProcs.ListOrder = 1
LEFT JOIN SS_IVC_InsuranceToFinancialClass as "Insurance"
ON IVC_PatientVisit.CurrentInsuranceCarriersId = Insurance.InsuranceNumber
LEFT JOIN IVC_PatientProfile
ON IVC_PatientVisit.PatientProfileId = IVC_PatientProfile.PatientProfileId
LEFT JOIN SS_Zip2FIPS
ON CASE
WHEN ISNUMERIC(LEFT(IVC_PatientProfile.Zip,5)) = 1  THEN LEFT(IVC_PatientProfile.Zip,5)
END LIKE SS_Zip2FIPS.ZIP_String
LEFT JOIN IVC_MedLists as "Modifier1"
ON Modifier1MId = Modifier1.MedListsId
LEFT JOIN IVC_MedLists as "Modifier2"
ON Modifier2MId = Modifier2.MedListsId
LEFT JOIN IVC_MedLists as "Modifier3"
ON Modifier3MId = Modifier3.MedListsId
LEFT JOIN IVC_MedLists as "Modifier4"
ON Modifier4MId = Modifier4.MedListsId
LEFT JOIN IVC_PatientVisitDiags as "Diags1"
ON IVC_PatientVisit.PatientVisitId = Diags1.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags1 = Diags1.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags2"
ON IVC_PatientVisit.PatientVisitId = Diags2.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags2 = Diags2.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags3"
ON IVC_PatientVisit.PatientVisitId = Diags3.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags3 = Diags3.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags4"
ON IVC_PatientVisit.PatientVisitId = Diags4.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags4 = Diags4.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags5"
ON IVC_PatientVisit.PatientVisitId = Diags5.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags5 = Diags5.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags6"
ON IVC_PatientVisit.PatientVisitId = Diags6.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags6 = Diags6.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags7"
ON IVC_PatientVisit.PatientVisitId = Diags7.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags7 = Diags7.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags8"
ON IVC_PatientVisit.PatientVisitId = Diags8.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags8 = Diags8.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags9"
ON IVC_PatientVisit.PatientVisitId = Diags9.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags9 = Diags9.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags10"
ON IVC_PatientVisit.PatientVisitId = Diags10.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags10 = Diags10.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags11"
ON IVC_PatientVisit.PatientVisitId = Diags11.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags11 = Diags11.ListOrder
LEFT JOIN IVC_PatientVisitDiags as "Diags12"
ON IVC_PatientVisit.PatientVisitId = Diags12.PatientVisitId AND IVC_PatientVisitProcs.PatientVisitDiags12 = Diags12.ListOrder
LEFT JOIN IVC_DoctorFacility as "PerformingDoctor"
ON IVC_PatientVisit.DoctorId = PerformingDoctor.DoctorFacilityId
LEFT JOIN IVC_DoctorFacility as "ReferringDoctor"
ON IVC_PatientVisit.ReferringDoctorId = ReferringDoctor.DoctorFacilityId
LEFT JOIN IVC_MedLists
ON IVC_PatientProfile.ReferenceSourceMId = IVC_MedLists.MedListsId
LEFT JOIN IVC_Language
ON IVC_PatientProfile.LanguageId = IVC_Language.LanguageId
LEFT JOIN IVC_MedLists as "Ethnicity"
ON IVC_PatientProfile.EthnicityMId = Ethnicity.MedListsId
LEFT JOIN ZZ_Contact
ON ReferringDoctor.NPI LIKE ZZ_Contact.LKL3__NPI__C
AND NOT (
	IVC_PatientVisit.ReferringDoctorId = 27
	OR IVC_PatientVisit.ReferringDoctorId = 17
	OR IVC_PatientVisit.ReferringDoctorId = 26
	OR IVC_PatientVisit.ReferringDoctorId = 23
	OR IVC_PatientVisit.ReferringDoctorId = 24
	OR IVC_PatientVisit.ReferringDoctorId = 415
	OR IVC_PatientVisit.ReferringDoctorId = 25
	OR IVC_PatientVisit.ReferringDoctorId = 1328
	OR IVC_PatientVisit.ReferringDoctorId = 28
	OR IVC_PatientVisit.ReferringDoctorId = 745
)
LEFT JOIN ZZ_Account as TaskAccount
ON ZZ_Contact.ACCOUNTID LIKE TaskAccount.ID
LEFT JOIN ZZ_Account as ParentAccount
ON TaskAccount.PARENTID LIKE ParentAccount.ID
LEFT JOIN CREDIT_TYPES
ON CREDIT_TYPES.[SOURCE] LIKE 'Centricity' AND IVC_Transactions.ActionTypeMId = CREDIT_TYPES.KEY_NUM
LEFT JOIN (
	SELECT DISTINCT
	CAST(IVC_PatientVisit.Visit as DATE) as Visit,
	IVC_PatientVisit.PatientProfileId
	FROM
	IVC_PatientVisit
) AS Visit
ON IVC_PatientVisit.PatientProfileId = Visit.PatientProfileId AND IVC_PaymentMethod.DateOfEntry = Visit.Visit

WHERE (IVC_Transactions.Action LIKE 'P' OR IVC_Transactions.Action LIKE 'A')
AND IVC_PatientVisit.CompanyId <> 3
AND IVC_PaymentMethod.DateOfEntry <= GETDATE()


DROP TABLE #CPU_TRANS_Charges